logging:
  path: ${user.home}/log/ark-user-registration
  custom:
    level: debug
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/arkdb
    username: ark
    password: ark
