logging:
  path: ${user.home}/log/ark-batch-runner
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/arkdb
    username: ark
    password: ark
  job-datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/arkdb
    username: ark
    password: ark
