logging:
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS},%X{sessionId},%X{remoteAddr},%level,%thread,%logger,%X{className},%X{methodName},%m%n'
spring:
  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
  messages:
    basename: messages,ValidationMessages
