spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_arkdb
    username: ark
    password: ark
  job-datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jobdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: sa
    password: ''
